Don't allow '/' to begin a branch name (#2534)
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

diff --git a/script/validate_branch_name b/script/validate_branch_name
--- a/script/validate_branch_name
+++ b/script/validate_branch_name
@@ -42,6 +42,15 @@ case "$BRANCH_NAME" in
     ;;
 esac
 
+# Reject branch names starting with /
+# (these could be confused as being an absolute path)
+case "$BRANCH_NAME" in
+  /*)
+    echo "ERROR: Branch name must not start with '/': $BRANCH_NAME" >&2
+    exit 1
+    ;;
+esac
+
 # Reject branch names including ..
 # (these could escape up a directory)
 case "$BRANCH_NAME" in
